# Generated by Django 5.1 on 2025-02-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customusermodel_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusermodel',
            old_name='fullname',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='last_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
