# Generated by Django 5.1 on 2025-02-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userprofilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
