# Generated by Django 5.1 on 2025-02-11 12:17

import account.models.forgot_password_token
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customusermodel_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPasswordTokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField(default=account.models.forgot_password_token.get_expiry_date)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forgot_password_tokens', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Forgot_password_token',
                'verbose_name_plural': 'Forgot_password_tokens',
                'db_table': 'forgot_password_token',
                'unique_together': {('user', 'is_used')},
            },
        ),
    ]
