# Generated by Django 5.1 on 2025-02-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_forgotpasswordtokenmodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='forgotpasswordtokenmodel',
            unique_together=set(),
        ),
    ]
