# Generated by Django 5.1 on 2025-02-16 16:53

import account.models.validate_user_token
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_forgotpasswordtokenmodel_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidateUserTokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField(default=account.models.validate_user_token.get_expiry_date)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validate_user_tokens', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Validate_user_token',
                'verbose_name_plural': 'Validate_users_tokens',
                'db_table': 'validate_user_token',
            },
        ),
    ]
