# Generated by Django 5.1 on 2025-02-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_validateusertokenmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
