# Generated by Django 5.1 on 2025-03-15 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_commentmodel_rating'),
        ('store', '0002_alter_storemodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='store.storemodel', verbose_name='products'),
        ),
    ]
