# Generated by Django 5.1 on 2025-03-15 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productmodel_store'),
        ('store', '0002_alter_storemodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.storemodel', verbose_name='products'),
        ),
    ]
