from .register import RegisterUserView, ValidateEmailView
from .update_profile import UpdateUserProfileView
from .reset_password import PasswordResetView
from .forgot_password import RequestForgotPasswordView, ConfirmForgotPasswordView